FROM node:alpine 
WORKDIR /app
COPY ./package.json ./package.json
COPY ./server.js ./server.js
COPY ./messageModel.js ./messageModel.js 
COPY ./roomModel.js ./roomModel.js
COPY ./userModel.js ./userModel.js
RUN npm install 
LABEL developer=si3mshady
EXPOSE 9000
CMD ["node", "server.js"]

# docker build . -f Dockerfile.node  -t si3mshady/slackclone-be:1